name: Lint Python Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry add trax
        poetry install
    - name: Lint with pysen
      run: |
        poetry run pysen run lint
